version: '2.4'
services:
  app:
    build: ./app
    container_name: ovdb_app
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=ovdb
      - MYSQL_PASSWORD=z63p7GU3UbXBtyWvLqEZcL79vswwZQMW
      - MYSQL_DATABASE=ovdb
      - MYSQL_PORT=3306
      - CACHE_LOCATION=redis://redis:6379/
      - ALLOWED_HOSTS=bridge.vantagecrypto.com,app
      - OV_HOST_URL=https://bridge.vantagecrypto.com/
      - OV_WEBSOCKET_HOST=websocket:8002
      - ADMIN_USER=admin
      - ADMIN_EMAIL=admin@gmail.com
      - ADMIN_PASSWORD=xvX9BCE7RXdMzG4V
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./app_file:/user/src/app/file
      - ./app_log:/usr/src/app/log
      - ./app_log_zip:/user/src/app/sectors/static/log_zip
    restart: always
  api:
    build: ./api
    container_name: ovdb_api
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=ovdb
      - MYSQL_PASSWORD=z63p7GU3UbXBtyWvLqEZcL79vswwZQMW
      - MYSQL_DATABASE=ovdb
      - MYSQL_PORT=3306
      - CACHE_LOCATION=redis://redis:6379/
      - ALLOWED_HOSTS=bridge.vantagecrypto.com
      - OV_APP_HOST=app:8000
    ports:
      - 8001:8001
    restart: always
  websocket:
    build: ./websocket
    container_name: ovdb_websocket
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=ovdb
      - MYSQL_PASSWORD=z63p7GU3UbXBtyWvLqEZcL79vswwZQMW
      - MYSQL_DATABASE=ovdb
      - MYSQL_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ALLOWED_HOSTS=bridge.vantagecrypto.com,websocket
      - OV_APP_HOST=app:8000
    ports:
      - 8002:8002
    restart: always
  webhook:
    build: ./webhook
    container_name: ovdb_webhook
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=ovdb
      - MYSQL_PASSWORD=z63p7GU3UbXBtyWvLqEZcL79vswwZQMW
      - MYSQL_DATABASE=ovdb
      - MYSQL_PORT=3306
      - ALLOWED_HOSTS=bridge.vantagecrypto.com
      - OV_APP_HOST=app:8000
    ports:
      - 8003:8003
    restart: always
  redis:
    image: redis:alpine
    container_name: ovdb_redis
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
    restart: always
  db:
    image: datajoint/mysql:5.7
    container_name: ovdb_db
    environment:
      - MYSQL_USER=ovdb
      - MYSQL_PASSWORD=z63p7GU3UbXBtyWvLqEZcL79vswwZQMW
      - MYSQL_DATABASE=ovdb
      - MYSQL_ROOT_PASSWORD=jQEbw5VVHesHnZsG7tS4
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql