version: '2.4'
services:
  app:
    build: ./app
    container_name: ovdb_app
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=ovdb
      - MYSQL_PASSWORD=z63p7GU3UbXBtyWvLqEZcL79vswwZQMW
      - MYSQL_DATABASE=ovdb
      - MYSQL_PORT=3306
      - WS_HOST=wsocket
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
  wsocket:
    build: ./wsocket
    container_name: ovdb_wsocket
    environment:
      - OV_HOST=app
    ports:
      - 8000:8000
    restart: always
  redis:
    image: redis:alpine
    container_name: ovdb_redis
    command: redis-server --appendonly yes
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_LOCATION=redis://redis:6379/
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
    restart: always
  db:
    image: datajoint/mysql:5.7
    container_name: ovdb_db
    environment:
      - MYSQL_USER=ovdb
      - MYSQL_PASSWORD=z63p7GU3UbXBtyWvLqEZcL79vswwZQMW
      - MYSQL_DATABASE=ovdb
      - MYSQL_ROOT_PASSWORD=jQEbw5VVHesHnZsG7tS4
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql