# Generated by Django 3.1.7 on 2021-09-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_tblbridge_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblbridge',
            name='test_field',
        ),
    ]
