# Generated by Django 3.1.7 on 2021-10-15 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_remove_tblbridge_test_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBLApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('unique_id', models.CharField(default='', max_length=255)),
                ('api_key', models.CharField(default='', max_length=255)),
                ('permission', models.JSONField(default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TBLAPIKEY',
            },
        ),
    ]
