# Generated by Django 3.1.7 on 2021-10-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_tblapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluser',
            name='unique_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
